FROM maven:3.8.1-openjdk-17 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM amazoncorretto:17
WORKDIR /app
COPY --from=builder /app/target/Sensor-Weather-0.0.1-SNAPSHOT.jar /app/sensor-service.jar
ENTRYPOINT ["java", "-jar", "/app/sensor-service.jar"]